spring.application.name=SmartExpenseAnalyzer

server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/smart_expense_db
spring.datasource.username=root
spring.datasource.password=Y@gne&h_2911
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
